#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoginMVC.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="QLDN")]
	public partial class DataBase_DangNhapDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertDangNhap_Admin(DangNhap_Admin instance);
    partial void UpdateDangNhap_Admin(DangNhap_Admin instance);
    partial void DeleteDangNhap_Admin(DangNhap_Admin instance);
    partial void InsertDangNhap_PhongVien(DangNhap_PhongVien instance);
    partial void UpdateDangNhap_PhongVien(DangNhap_PhongVien instance);
    partial void DeleteDangNhap_PhongVien(DangNhap_PhongVien instance);
    partial void InsertPhanQuyen(PhanQuyen instance);
    partial void UpdatePhanQuyen(PhanQuyen instance);
    partial void DeletePhanQuyen(PhanQuyen instance);
    #endregion
		
		public DataBase_DangNhapDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataBase_DangNhapDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataBase_DangNhapDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataBase_DangNhapDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}

        public DataBase_DangNhapDataContext():
            base(global::System.Configuration.ConfigurationManager.ConnectionStrings["QLDNConnectionString"].ConnectionString, mappingSource)
        {
			OnCreated();
        }

        public System.Data.Linq.Table<DangNhap_Admin> DangNhap_Admins
		{
			get
			{
				return this.GetTable<DangNhap_Admin>();
			}
		}
		
		public System.Data.Linq.Table<DangNhap_PhongVien> DangNhap_PhongViens
		{
			get
			{
				return this.GetTable<DangNhap_PhongVien>();
			}
		}
		
		public System.Data.Linq.Table<PhanQuyen> PhanQuyens
		{
			get
			{
				return this.GetTable<PhanQuyen>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DangNhap_Admin")]
	public partial class DangNhap_Admin : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_Admin;
		
		private string _TaiKhoan;
		
		private string _MatKhau;
		
		private System.Nullable<int> _ID_PhanQuyen;
		
		private EntityRef<PhanQuyen> _PhanQuyen;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_AdminChanging(int value);
    partial void OnID_AdminChanged();
    partial void OnTaiKhoanChanging(string value);
    partial void OnTaiKhoanChanged();
    partial void OnMatKhauChanging(string value);
    partial void OnMatKhauChanged();
    partial void OnID_PhanQuyenChanging(System.Nullable<int> value);
    partial void OnID_PhanQuyenChanged();
    #endregion
		
		public DangNhap_Admin()
		{
			this._PhanQuyen = default(EntityRef<PhanQuyen>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Admin", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int ID_Admin
		{
			get
			{
				return this._ID_Admin;
			}
			set
			{
				if ((this._ID_Admin != value))
				{
					this.OnID_AdminChanging(value);
					this.SendPropertyChanging();
					this._ID_Admin = value;
					this.SendPropertyChanged("ID_Admin");
					this.OnID_AdminChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TaiKhoan", DbType="VarChar(50)")]
		public string TaiKhoan
		{
			get
			{
				return this._TaiKhoan;
			}
			set
			{
				if ((this._TaiKhoan != value))
				{
					this.OnTaiKhoanChanging(value);
					this.SendPropertyChanging();
					this._TaiKhoan = value;
					this.SendPropertyChanged("TaiKhoan");
					this.OnTaiKhoanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MatKhau", DbType="VarChar(50)")]
		public string MatKhau
		{
			get
			{
				return this._MatKhau;
			}
			set
			{
				if ((this._MatKhau != value))
				{
					this.OnMatKhauChanging(value);
					this.SendPropertyChanging();
					this._MatKhau = value;
					this.SendPropertyChanged("MatKhau");
					this.OnMatKhauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_PhanQuyen", DbType="Int")]
		public System.Nullable<int> ID_PhanQuyen
		{
			get
			{
				return this._ID_PhanQuyen;
			}
			set
			{
				if ((this._ID_PhanQuyen != value))
				{
					if (this._PhanQuyen.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnID_PhanQuyenChanging(value);
					this.SendPropertyChanging();
					this._ID_PhanQuyen = value;
					this.SendPropertyChanged("ID_PhanQuyen");
					this.OnID_PhanQuyenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PhanQuyen_DangNhap_Admin", Storage="_PhanQuyen", ThisKey="ID_PhanQuyen", OtherKey="ID_PhanQuyen", IsForeignKey=true)]
		public PhanQuyen PhanQuyen
		{
			get
			{
				return this._PhanQuyen.Entity;
			}
			set
			{
				PhanQuyen previousValue = this._PhanQuyen.Entity;
				if (((previousValue != value) 
							|| (this._PhanQuyen.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._PhanQuyen.Entity = null;
						previousValue.DangNhap_Admins.Remove(this);
					}
					this._PhanQuyen.Entity = value;
					if ((value != null))
					{
						value.DangNhap_Admins.Add(this);
						this._ID_PhanQuyen = value.ID_PhanQuyen;
					}
					else
					{
						this._ID_PhanQuyen = default(Nullable<int>);
					}
					this.SendPropertyChanged("PhanQuyen");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DangNhap_PhongVien")]
	public partial class DangNhap_PhongVien : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_PhongVien;
		
		private string _TaiKhoan;
		
		private string _MatKhau;
		
		private System.Nullable<int> _ID_PhanQuyen;
		
		private EntityRef<PhanQuyen> _PhanQuyen;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_PhongVienChanging(int value);
    partial void OnID_PhongVienChanged();
    partial void OnTaiKhoanChanging(string value);
    partial void OnTaiKhoanChanged();
    partial void OnMatKhauChanging(string value);
    partial void OnMatKhauChanged();
    partial void OnID_PhanQuyenChanging(System.Nullable<int> value);
    partial void OnID_PhanQuyenChanged();
    #endregion
		
		public DangNhap_PhongVien()
		{
			this._PhanQuyen = default(EntityRef<PhanQuyen>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_PhongVien", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int ID_PhongVien
		{
			get
			{
				return this._ID_PhongVien;
			}
			set
			{
				if ((this._ID_PhongVien != value))
				{
					this.OnID_PhongVienChanging(value);
					this.SendPropertyChanging();
					this._ID_PhongVien = value;
					this.SendPropertyChanged("ID_PhongVien");
					this.OnID_PhongVienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TaiKhoan", DbType="VarChar(10)")]
		public string TaiKhoan
		{
			get
			{
				return this._TaiKhoan;
			}
			set
			{
				if ((this._TaiKhoan != value))
				{
					this.OnTaiKhoanChanging(value);
					this.SendPropertyChanging();
					this._TaiKhoan = value;
					this.SendPropertyChanged("TaiKhoan");
					this.OnTaiKhoanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MatKhau", DbType="VarChar(10)")]
		public string MatKhau
		{
			get
			{
				return this._MatKhau;
			}
			set
			{
				if ((this._MatKhau != value))
				{
					this.OnMatKhauChanging(value);
					this.SendPropertyChanging();
					this._MatKhau = value;
					this.SendPropertyChanged("MatKhau");
					this.OnMatKhauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_PhanQuyen", DbType="Int")]
		public System.Nullable<int> ID_PhanQuyen
		{
			get
			{
				return this._ID_PhanQuyen;
			}
			set
			{
				if ((this._ID_PhanQuyen != value))
				{
					if (this._PhanQuyen.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnID_PhanQuyenChanging(value);
					this.SendPropertyChanging();
					this._ID_PhanQuyen = value;
					this.SendPropertyChanged("ID_PhanQuyen");
					this.OnID_PhanQuyenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PhanQuyen_DangNhap_PhongVien", Storage="_PhanQuyen", ThisKey="ID_PhanQuyen", OtherKey="ID_PhanQuyen", IsForeignKey=true)]
		public PhanQuyen PhanQuyen
		{
			get
			{
				return this._PhanQuyen.Entity;
			}
			set
			{
				PhanQuyen previousValue = this._PhanQuyen.Entity;
				if (((previousValue != value) 
							|| (this._PhanQuyen.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._PhanQuyen.Entity = null;
						previousValue.DangNhap_PhongViens.Remove(this);
					}
					this._PhanQuyen.Entity = value;
					if ((value != null))
					{
						value.DangNhap_PhongViens.Add(this);
						this._ID_PhanQuyen = value.ID_PhanQuyen;
					}
					else
					{
						this._ID_PhanQuyen = default(Nullable<int>);
					}
					this.SendPropertyChanged("PhanQuyen");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PhanQuyen")]
	public partial class PhanQuyen : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_PhanQuyen;
		
		private string _PhanQuyen_Ten;
		
		private EntitySet<DangNhap_Admin> _DangNhap_Admins;
		
		private EntitySet<DangNhap_PhongVien> _DangNhap_PhongViens;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_PhanQuyenChanging(int value);
    partial void OnID_PhanQuyenChanged();
    partial void OnPhanQuyen_TenChanging(string value);
    partial void OnPhanQuyen_TenChanged();
    #endregion
		
		public PhanQuyen()
		{
			this._DangNhap_Admins = new EntitySet<DangNhap_Admin>(new Action<DangNhap_Admin>(this.attach_DangNhap_Admins), new Action<DangNhap_Admin>(this.detach_DangNhap_Admins));
			this._DangNhap_PhongViens = new EntitySet<DangNhap_PhongVien>(new Action<DangNhap_PhongVien>(this.attach_DangNhap_PhongViens), new Action<DangNhap_PhongVien>(this.detach_DangNhap_PhongViens));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_PhanQuyen", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int ID_PhanQuyen
		{
			get
			{
				return this._ID_PhanQuyen;
			}
			set
			{
				if ((this._ID_PhanQuyen != value))
				{
					this.OnID_PhanQuyenChanging(value);
					this.SendPropertyChanging();
					this._ID_PhanQuyen = value;
					this.SendPropertyChanged("ID_PhanQuyen");
					this.OnID_PhanQuyenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PhanQuyen_Ten", DbType="NVarChar(50)")]
		public string PhanQuyen_Ten
		{
			get
			{
				return this._PhanQuyen_Ten;
			}
			set
			{
				if ((this._PhanQuyen_Ten != value))
				{
					this.OnPhanQuyen_TenChanging(value);
					this.SendPropertyChanging();
					this._PhanQuyen_Ten = value;
					this.SendPropertyChanged("PhanQuyen_Ten");
					this.OnPhanQuyen_TenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PhanQuyen_DangNhap_Admin", Storage="_DangNhap_Admins", ThisKey="ID_PhanQuyen", OtherKey="ID_PhanQuyen")]
		public EntitySet<DangNhap_Admin> DangNhap_Admins
		{
			get
			{
				return this._DangNhap_Admins;
			}
			set
			{
				this._DangNhap_Admins.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PhanQuyen_DangNhap_PhongVien", Storage="_DangNhap_PhongViens", ThisKey="ID_PhanQuyen", OtherKey="ID_PhanQuyen")]
		public EntitySet<DangNhap_PhongVien> DangNhap_PhongViens
		{
			get
			{
				return this._DangNhap_PhongViens;
			}
			set
			{
				this._DangNhap_PhongViens.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_DangNhap_Admins(DangNhap_Admin entity)
		{
			this.SendPropertyChanging();
			entity.PhanQuyen = this;
		}
		
		private void detach_DangNhap_Admins(DangNhap_Admin entity)
		{
			this.SendPropertyChanging();
			entity.PhanQuyen = null;
		}
		
		private void attach_DangNhap_PhongViens(DangNhap_PhongVien entity)
		{
			this.SendPropertyChanging();
			entity.PhanQuyen = this;
		}
		
		private void detach_DangNhap_PhongViens(DangNhap_PhongVien entity)
		{
			this.SendPropertyChanging();
			entity.PhanQuyen = null;
		}
	}
}
#pragma warning restore 1591
