<?xml version="1.0" encoding="utf-8"?><Database Name="QLDN" Class="DataBase_DangNhapDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Table Name="dbo.DangNhap_Admin" Member="DangNhap_Admins">
    <Type Name="DangNhap_Admin">
      <Column Name="ID_Admin" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TaiKhoan" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="MatKhau" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ID_PhanQuyen" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="PhanQuyen_DangNhap_Admin" Member="PhanQuyen" ThisKey="ID_PhanQuyen" OtherKey="ID_PhanQuyen" Type="PhanQuyen" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.DangNhap_PhongVien" Member="DangNhap_PhongViens">
    <Type Name="DangNhap_PhongVien">
      <Column Name="ID_PhongVien" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TaiKhoan" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="MatKhau" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="ID_PhanQuyen" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="PhanQuyen_DangNhap_PhongVien" Member="PhanQuyen" ThisKey="ID_PhanQuyen" OtherKey="ID_PhanQuyen" Type="PhanQuyen" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.PhanQuyen" Member="PhanQuyens">
    <Type Name="PhanQuyen">
      <Column Name="ID_PhanQuyen" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="PhanQuyen_Ten" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="PhanQuyen_DangNhap_Admin" Member="DangNhap_Admins" ThisKey="ID_PhanQuyen" OtherKey="ID_PhanQuyen" Type="DangNhap_Admin" />
      <Association Name="PhanQuyen_DangNhap_PhongVien" Member="DangNhap_PhongViens" ThisKey="ID_PhanQuyen" OtherKey="ID_PhanQuyen" Type="DangNhap_PhongVien" />
    </Type>
  </Table>
</Database>