<?xml version="1.0" encoding="utf-8"?><Database Name="DemoWinform" Class="DatabaseDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=MSI\SQLEXPRESS;Initial Catalog=DemoWinform;Integrated Security=True" SettingsObjectName="DemoControlNangCao02.Properties.Settings" SettingsPropertyName="DemoWinformConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.tbl_SV" Member="tbl_SVs">
    <Type Name="tbl_SV">
      <Column Name="MSSV" Type="System.String" DbType="NVarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="HoTen" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="MatKhau" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="isDelete" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="DeleteTime" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="GioiTinh" Type="System.String" DbType="NVarChar(5)" CanBeNull="true" />
      <Column Name="NgaySinh" Type="System.DateTime" DbType="Date" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_taikhoan" Member="tbl_taikhoans">
    <Type Name="tbl_taikhoan">
      <Column Name="ID" Type="System.String" DbType="NVarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TaiKhoan" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="MatKhau" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
    </Type>
  </Table>
</Database>